### ISSUE TITLE
Client.aliveTimer not a Timeout

### ISSUE THREAD

**Issue by primetoxinz** [rakusan2/FRC-NT-Client#1]
When attempting the basic 
```
ntClient.start((con, err) => {
    console.log({con, err});
    if (!con)
      throw err;
    }
  );
```
it throws 
```
Uncaught TypeError: this.aliveTimer.unref is not a function
    at Client.write (/home/tyler/Programming/FRCDashboard/node_modules/wpilib-nt-client/index.js:452)
    at aliveTimer.setTimeout (/home/tyler/Programming/FRCDashboard/node_modules/wpilib-nt-client/index.js:451)
```
Meaning that for some reason, even though `this.aliveTimer` is always initialized via `setTimeout` it is not a Timeout. 
Any ideas?

**Comment by primetoxinz** [comment]
Appears this is due to running the Client in the Electron render process, which is not a normal Node environment and has it's own `setTimeout` function. It would be appreciated if you added a note that this has to be initializing in the Node main.

**Comment by rakusan2** [comment]
This is an issue with unref not existing on the Timer Object that the renderer process uses

**Comment by rakusan2** [comment]
Version 1.2.4 should now work in electrons renderer process
