### ISSUE TITLE
stop() and destroy() don't work

### ISSUE THREAD

**Issue by silentstormm** [rakusan2/FRC-NT-Client#9]
I have this little bit of code:

```
ipc.on('disconnect', event => {
  console.log('disconnecting...')
  client.stop()
  if(client.isConnected()) {
    client.destroy()
  }
  console.log(client.isConnected())
  event.reply('disconnected')
})
```

The callback is called and the log is logged, but the client still is connected or trying to connect.

**Comment by rakusan2** [comment]
`client.stop()` is not synchronous
Its purpose is to simply announce to the server that the client wants to end the connection.
Therefore calling `client.isConnected()` will still return `true` as it is still possible for the server to send something back.

`client.destroy()` on the other hand will not wait for the server and just close the connection right away.
The reason why `client.isConnected()` returned false right after is simply that the isConnected variable is controlled by the "end" event on the socket which would be called after your function.

Also thanks to this I have found that the keep-alive packet kept being sent after either of these methods were called.

1.7.2 fixes the keep-alive bug and makes the `destroy()` method set connected to false before the "end" event is called.

**Comment by silentstormm** [comment]
I've upgraded to 1.7.2 and it does indeed work as intended. Thanks!
